name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Tag to release
        type: string
        required: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macos
            arch: aarch64
          - os: ubuntu-24.04-arm
            platform: linux
            arch: aarch64
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Blueshift
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
          path: blueshift
      - name: Check out Wattle
        uses: actions/checkout@v4
        with:
          repository: pyrmont/wattle
          path: wattle
      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build Wattle
        run: zig build
        working-directory: wattle
      - name: Build Blueshift
        run: ../wattle/zig-out/bin/wattle -p ../wattle/zig-out build exe --release fast
        working-directory: blueshift
      - name: Package Blueshift
        run: |
          package="blueshift-${{ inputs.version }}"
          mkdir "$package"
          cp zig-out/bin/blues man/man1/blues.1 LICENSE README.md "$package/"
          tar -czf "${package}-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz" "$package"
        working-directory: blueshift
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ matrix.arch }}
          path: blueshift/blueshift-${{ inputs.version }}-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts
          merge-multiple: true
      - name: Draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ./artifacts/*
          overwrite_files: false
          tag_name: ${{ inputs.version }}
